### ISSUE TITLE
Grunt task breaks at directory-colorfy

### ISSUE THREAD

**Issue by duyenho** [filamentgroup/directory-colorfy#28]
I'm trying to run a `grunt svg` task which breaks below:

```
Running "directory-colorfy" task
Error: Command failed: /Users/dho/front-end/node_modules/directory-colorfy/node_modules/phantomjs/lib/phantom/bin/phantomjs /Users/dho/front-end/node_modules/directory-colorfy/lib/phantomscript.js %3Csvg%20data-name=%22Layer%201%22%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%2212.97%22%20height=%2210.07%22%20viewBox=%220%200%2012.97%2010.07%22%3E%3Ctitle%3Etick%3C/title%3E%3Cpath%20d=%22M5%2010.07L0%205.34l1.78-1.7%203.1%203L11.12%200%2013%201.61z%22%20fill=%22#ce0058%22/%3E%3C/svg%3E tick-white.svg #ffffff

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

I tried reinstalling grunticon globally and running another npm install in my project folder but keep getting the same error. Do you have any hints as to what's causing the task to break or any suggestions on how to resolve the issue?

**Comment by jefflembeck** [comment]
@duyenho which version of grunticon are you running? which version of node? which OS?

**Comment by duyenho** [comment]
All good @jefflembeck.

Running node v4.4.6 and installed:
```
"directory-colorfy": "2.2.0",
"directory-encoder": "0.9.1",
```

Thank you.

**Comment by zachleat** [comment]
Can you retest after `directory-colorfy` 3.0 is released? It’s upcoming.
